/**
 * The demo's static files, served in dev and emitted on build.
 *
 * Two kinds of request in the app are not `fetch` calls, so the in-page mock
 * (src/mock) cannot answer them: the document preview is an `<iframe src>` and
 * the download is an `<a href>`. Both point at `/api/applications/artifacts/
 * <id>/{preview,export}`, so the build puts a real file at each of those paths
 * — written by scripts/build_seed.py from the real backend's own renderer — and
 * nginx.conf serves them as HTML and .docx. The seed itself (`/demo-data/*.json`)
 * is fetched by the mock rather than bundled: it is most of the bytes, and the
 * page should not parse a megabyte of documents before its first paint.
 *
 * Downloads are named by a header, not by their path, so the build also writes
 * `dist-nginx/export-names.conf`: one nginx `map` line per document, giving the
 * `Content-Disposition` the real API would have sent.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Plugin } from "vite";

const HERE = dirname(fileURLToPath(import.meta.url));
const STATIC = join(HERE, "static");
const ARTIFACT = /^\/api\/applications\/artifacts\/(\d+)\/(preview|export)$/;
const DATA = /^\/demo-data\/([\w-]+\.json)$/;
const DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

function exportNames(): Record<string, string> {
  return JSON.parse(readFileSync(join(STATIC, "export-names.json"), "utf8"));
}

export function demoFiles(): Plugin {
  return {
    name: "demo-files",
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        const path = (request.url ?? "").split("?")[0];
        const artifact = ARTIFACT.exec(path);
        const data = DATA.exec(path);
        try {
          if (artifact) {
            const [, id, kind] = artifact;
            const file = join(STATIC, "artifacts", `${id}.${kind === "preview" ? "html" : "docx"}`);
            const body = readFileSync(file);
            response.setHeader("Content-Type", kind === "preview" ? "text/html; charset=utf-8" : DOCX);
            if (kind === "export") {
              response.setHeader("Content-Disposition", `attachment; filename="${exportNames()[id]}"`);
            }
            response.end(body);
            return;
          }
          if (data) {
            response.setHeader("Content-Type", "application/json");
            response.end(readFileSync(join(STATIC, "seed", data[1])));
            return;
          }
        } catch {
          response.statusCode = 404;
          response.end("Not in the demo.");
          return;
        }
        next();
      });
    },
    generateBundle() {
      for (const name of readdirSync(join(STATIC, "artifacts"))) {
        const [id, extension] = name.split(".");
        this.emitFile({
          type: "asset",
          fileName: `api/applications/artifacts/${id}/${extension === "html" ? "preview.html" : "export.docx"}`,
          source: readFileSync(join(STATIC, "artifacts", name)),
        });
      }
      for (const name of readdirSync(join(STATIC, "seed"))) {
        this.emitFile({ type: "asset", fileName: `demo-data/${name}`, source: readFileSync(join(STATIC, "seed", name)) });
      }
    },
    closeBundle() {
      const out = resolve(HERE, "..", "dist-nginx");
      mkdirSync(out, { recursive: true });
      const lines = Object.entries(exportNames())
        .sort(([a], [b]) => Number(a) - Number(b))
        .map(([id, file]) => `  /api/applications/artifacts/${id}/export "attachment; filename=\\"${file}\\"";`);
      writeFileSync(
        join(out, "export-names.conf"),
        "# Generated by demo/vite-demo-files.ts from demo/static/export-names.json.\n" +
          "# The filename each document downloads under — the header the real API sends.\n" +
          `map $request_uri $export_disposition {\n  default "";\n${lines.join("\n")}\n}\n`,
      );
    },
  };
}
